### ISSUE TITLE
Custom decoder for date

### ISSUE THREAD

**Issue by staticdreams** [carson-katri/swift-request#16]
How would I go about decoding custom data, such as custom formatted dates?
Do we have access to ``JSONDecoder`` so we can do something like this: ? 

    struct Event: Codable {
        var name: String?
        var createdDate: Date?
    }
  
    extension DateFormatter {
        static let dateFormatter: DateFormatter = {
         let formatter = DateFormatter()
         formatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
          return formatter
        }()
    }

    let decoder: JSONDecoder = JSONDecoder()
    decoder.dateDecodingStrategy = .formatted(.dateFormatter)

**Comment by carson-katri** [comment]
You can use `onData` and manually perform Json decoding:
```swift
Request {
    ...
}
.onData { data in
    let decoder = JSONDecoder()
    ...
}
```

**Comment by staticdreams** [comment]
Thanks I will try that. 
Sorry for stupid questions, I couldn't find an example in the docs :)

**Comment by carson-katri** [comment]
No problem! Let me know if you have any other questions.
