### ISSUE TITLE
How to set the timeout

### ISSUE THREAD

**Issue by ly410726** [carson-katri/swift-request#26]
How to set the timeout

**Comment by carson-katri** [comment]
There currently is no way to change the default URLSession timeout property.

It should be trivial to add something like:

```swift
Request {
    ...
    Timeout(30, for: .request)
    Timeout(60, for: .resource)
}
```

Then we can use the `URLSessionConfiguration` to change this internally. I'll work on this.

**Comment by carson-katri** [comment]
Please try out the dev branch. I've added timeout in #27
