### ISSUE TITLE
Json: Access nested optional value 

### ISSUE THREAD

**Issue by danousna** [carson-katri/swift-request#28]
Hi there,

Thanks for the library.

I am using an api which returns the following json : 
```js
{
  "object": {
     "name": "Bob",
        // ...
  },
  "some": "other value"
}
```

The `object` key can sometimes be empty.

However, I want to access the `name` key using my Json object. But when the `object` is empty, my app crashes because of course, it cannot get to the `name` key (`Could not cast value of type 'NSNull' (0x...........) to 'NSDictionary'`).

I can't figure out how to test for this.

Thanks for the help.

**Comment by carson-katri** [comment]
Is using `Codable` an option? If so you could mark `object` as optional:

```swift
struct MyData : Codable {
  let object: Object?
  let some: String

  struct Object : Codable {
    let name: String
    // ...
  }
}
```

Then `Request` can handle decoding it for you

**Comment by danousna** [comment]
Indeed it works.

Thanks for the help !
