### ISSUE TITLE
The 'Body' confilct

### ISSUE THREAD

**Issue by yagamis** [carson-katri/swift-request#32]
Dear carson-katri:

A XCode compile error occored while I added Request 'Body' :  

`Request {
            Url(createOrder)
            Method(.post)
            Header.ContentType(.json)
            Body(Json(data).stringified)    //Type 'MyCustomSwiftUIView.Body' (aka 'some View') has no member 'init'
        }`

How to fix it? Thanks!

**Comment by carson-katri** [comment]
Please see my solution [here](https://github.com/carson-katri/swift-request/issues/23#issuecomment-631544711).

I’ll add this type alias to the library itself since this is a common use case/problem.

**Comment by yagamis** [comment]
You are my savor! !! And I hope the update come soon, can't wait!

An totoaly replace of Alamofire , Request is the ONE!!! 🔥🔥🔥

Thanks for your GREAT WORK again!

**Comment by carson-katri** [comment]
Thank you! 🙏

**Comment by carson-katri** [comment]
This has been implemented by #33
