### ISSUE TITLE
Merge two Url with + operator

### ISSUE THREAD

**Issue by brennobemoura** [carson-katri/swift-request#36]
I would like to add two URL to create a new one, for example:

`
    Url("https://example.com/api/v1") + Url("/settings")
`

But, I believe that we can add one Url with a string too like that:

`
    func + (_ url: Url, _ complementary: String) -> Url {
        Url("\(url.value ?? "")\(complementary)")
     }
`

**Comment by carson-katri** [comment]
Great suggestion, feel free to make a PR. I agree that `Url` + `String` _and_ `Url` + `Url` would be good.
