### ISSUE TITLE
RequestImage remove animation

### ISSUE THREAD

**Issue by ca13ra1** [carson-katri/swift-request#48]
Setting nil doesn't seem to remove animation from `RequestImage`, testing on iOS 14.

```swift
RequestImage(Url("url_here"))
   .animation(nil)
```

**Comment by carson-katri** [comment]
You should be able to pass the desired animation directly into `RequestImage`:

`RequestImage(url, animation: nil)`

**Comment by ca13ra1** [comment]
I'm getting `'nil' is not compatible with expected argument type 'Animation'`

**Comment by carson-katri** [comment]
I made `Animation` optional in the `swiftui` branch, so that should now be valid.

**Comment by ca13ra1** [comment]
Thank you again! 😊

**Comment by carson-katri** [comment]
No problem, thanks for catching these bugs

**Comment by ca13ra1** [comment]
Anytime!
