### ISSUE TITLE
Question: RequestImage support for SVG images?

### ISSUE THREAD

**Issue by ca13ra1** [carson-katri/swift-request#55]
Are SVG images supported or could be supported by `RequestImage`? The API I'm using only allows for `SVG` unfortunately.

**Comment by carson-katri** [comment]
SwiftUI's `Image` doesn't support SVG AFAIK, so no... You may be able to convert the raw SVG data to a `Shape`/`Path`, or even a PNG first, but `swift-request` does not handle that case.

**Comment by ca13ra1** [comment]
After I was looking into this, I noticed SVG’s weren’t supported. I ended up using a Python script to get all the SVG’s and converted them to PNG’s.
